# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/liao/selfcppdev/Ryao

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/liao/selfcppdev/Ryao

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"eigen\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liao/selfcppdev/Ryao/CMakeFiles /home/liao/selfcppdev/Ryao//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liao/selfcppdev/Ryao/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/main.dir/build.make src/CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named igl_core

# Build rule for target.
igl_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 igl_core
.PHONY : igl_core

# fast build rule for target.
igl_core/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libigl-build/CMakeFiles/igl_core.dir/build.make _deps/libigl-build/CMakeFiles/igl_core.dir/build
.PHONY : igl_core/fast

#=============================================================================
# Target rules for targets named igl_opengl

# Build rule for target.
igl_opengl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 igl_opengl
.PHONY : igl_opengl

# fast build rule for target.
igl_opengl/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libigl-build/CMakeFiles/igl_opengl.dir/build.make _deps/libigl-build/CMakeFiles/igl_opengl.dir/build
.PHONY : igl_opengl/fast

#=============================================================================
# Target rules for targets named igl_glfw

# Build rule for target.
igl_glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 igl_glfw
.PHONY : igl_glfw

# fast build rule for target.
igl_glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libigl-build/CMakeFiles/igl_glfw.dir/build.make _deps/libigl-build/CMakeFiles/igl_glfw.dir/build
.PHONY : igl_glfw/fast

#=============================================================================
# Target rules for targets named igl_imgui

# Build rule for target.
igl_imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 igl_imgui
.PHONY : igl_imgui

# fast build rule for target.
igl_imgui/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libigl-build/CMakeFiles/igl_imgui.dir/build.make _deps/libigl-build/CMakeFiles/igl_imgui.dir/build
.PHONY : igl_imgui/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libigl-build/CMakeFiles/imgui.dir/build.make _deps/libigl-build/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named imguizmo

# Build rule for target.
imguizmo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imguizmo
.PHONY : imguizmo

# fast build rule for target.
imguizmo/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libigl-build/CMakeFiles/imguizmo.dir/build.make _deps/libigl-build/CMakeFiles/imguizmo.dir/build
.PHONY : imguizmo/fast

#=============================================================================
# Target rules for targets named igl_copyleft_tetgen

# Build rule for target.
igl_copyleft_tetgen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 igl_copyleft_tetgen
.PHONY : igl_copyleft_tetgen

# fast build rule for target.
igl_copyleft_tetgen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libigl-build/CMakeFiles/igl_copyleft_tetgen.dir/build.make _deps/libigl-build/CMakeFiles/igl_copyleft_tetgen.dir/build
.PHONY : igl_copyleft_tetgen/fast

#=============================================================================
# Target rules for targets named igl_copyleft_core

# Build rule for target.
igl_copyleft_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 igl_copyleft_core
.PHONY : igl_copyleft_core

# fast build rule for target.
igl_copyleft_core/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libigl-build/CMakeFiles/igl_copyleft_core.dir/build.make _deps/libigl-build/CMakeFiles/igl_copyleft_core.dir/build
.PHONY : igl_copyleft_core/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glad-build/CMakeFiles/glad.dir/build.make _deps/glad-build/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glfw-build/src/CMakeFiles/glfw.dir/build.make _deps/glfw-build/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named tetgen

# Build rule for target.
tetgen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tetgen
.PHONY : tetgen

# fast build rule for target.
tetgen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tetgen-build/CMakeFiles/tetgen.dir/build.make _deps/tetgen-build/CMakeFiles/tetgen.dir/build
.PHONY : tetgen/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... glad"
	@echo "... glfw"
	@echo "... igl_copyleft_core"
	@echo "... igl_copyleft_tetgen"
	@echo "... igl_core"
	@echo "... igl_glfw"
	@echo "... igl_imgui"
	@echo "... igl_opengl"
	@echo "... imgui"
	@echo "... imguizmo"
	@echo "... main"
	@echo "... tetgen"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

